language: java
jdk: oraclejdk8

env:
  global:
    - CC_TEST_REPORTER_ID=fa130e273291a2afaa11e080a243fe5965f9535c6065b72f470c915d3e322e23

before_install:
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)
